steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/mlb-pred:latest','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/mlb-pred:latest']
images:
- 'gcr.io/$PROJECT_ID/mlb-pred:latest'